# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
    - name: Install Ubuntu dependencies
      run: >
        sudo apt-get update -q && sudo apt-get install
        --no-install-recommends -y xvfb python3-dev python3-gi
        python3-gi-cairo gir1.2-gtk-3.0 libgirepository1.0-dev
        libcairo2-dev enchant
    - name: Install dependencies
      run: |
        sudo python3 -m pip install --upgrade pip
        sudo pip3 install flake8 nose mypy
        sudo pip3 install --upgrade keyrings.alt
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
    - name: Test with nose
      run: |
        xvfb-run -a nosetests -v gourmet/tests/test_*
    - name: Test with mypy
      run: |
        mypy gourmet/
      if: always()
